# Generated by Django 4.1.7 on 2023-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, verbose_name='Enter Your Name')),
                ('Email', models.EmailField(max_length=100, verbose_name='xyz@gmail.com')),
                ('Phone', models.IntegerField(default=0, max_length=10)),
                ('Adress', models.CharField(max_length=200, verbose_name='xyz nagar')),
                ('Message_Subject', models.CharField(max_length=1000, verbose_name='My subject')),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
