# Generated by Django 4.1.7 on 2023-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_contactform_adress_alter_contactform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='photo',
            field=models.ImageField(default='image/Screenshot from 2022-06-17 08-43-48.png', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='Phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
