# Generated by Django 4.1.7 on 2023-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_contactform_photo_alter_contactform_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='photo',
            field=models.ImageField(default='Screenshot from 2022-06-17 08-43-48.png', upload_to=''),
        ),
    ]
