# Generated by Django 4.1.7 on 2023-04-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Boy', max_length=100)),
                ('email', models.EmailField(default='aryanraj3041@gmail.com', max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('headlines', models.CharField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('Profile_image', models.ImageField(default='image/boy.JPG', upload_to='')),
                ('social_twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('social_github', models.CharField(blank=True, max_length=100, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('social_website', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='aryanraj3041@gmail.com', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='user.profile')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.profile')),
            ],
        ),
    ]
