# Generated by Django 4.1.7 on 2023-04-01 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='no subject', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_image',
            field=models.ImageField(default='profile/boy.JPG', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
